      - name: Write pubspec.yaml
        run: |
          cat <<EOF > pubspec.yaml
          name: ${{ steps.sanitize.outputs.sanitized_name }}
          description: "Universal App"
          publish_to: none
          version: 1.0.0+1

          environment:
            sdk: ">=3.6.0 <4.0.0"

          dependencies:
            flutter:
              sdk: flutter
            camera: ^0.11.0+2
            permission_handler: ^11.3.1
            path_provider: ^2.1.4
            flutter_background_service: ^5.1.0
            flutter_local_notifications: ^17.2.3
            workmanager: ^0.5.2
            video_player: ^2.9.2
            ffmpeg_kit_flutter_full_gpl: ^6.0.3
            image_picker: ^1.1.2
            # یہاں ورژن کو اپ ڈیٹ کر دیا گیا ہے
            flutter_webrtc: ^1.1.2
            livekit_client: ^2.5.3
            dio: ^5.7.0
            shared_preferences: ^2.3.3
            sqflite: ^2.3.3+1
            device_info_plus: ^11.1.0

          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^5.0.0

          dependency_overrides:
            path: 1.9.0
            meta: 1.15.0
            # اضافی تحفظ کے لیے یہاں بھی ورژن لاک کر دیا ہے
            flutter_webrtc: 1.1.2

          flutter:
            uses-material-design: true
          EOF
