name: Setup Structure and Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Flutter Structure if missing
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "Creating basic Flutter structure with valid name..."
            # پراجیکٹ کا نام چھوٹے حروف میں دینا ضروری ہے
            flutter create --project-name system_pro_codestuido .
          else
            echo "Project structure already exists."
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: System-Pro-APK
          path: build/app/outputs/flutter-apk/app-release.apk
