name: System Pro Flutter Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # تاکہ آپ خود بھی بٹن دبا کر بلڈ شروع کر سکیں

jobs:
  cleanup_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean Old Files
        run: |
          # یہ کمانڈ پچھلے کسی بھی عارضی بلڈ ڈیٹا کو صاف کرے گی
          rm -rf build/
          
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: System-Pro-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
